# -*- coding: utf-8 -*-
"""DoAnPH1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ryiVS28WfcWNj5JtQAplElb5Kdp8j7so
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/DoAnNganh/DuLieu/credit_risk_dataset.csv')

df = df.rename(columns={
    'person_age': 'Age', 'person_income': 'Income', 'person_home_ownership':'Home',
    'person_emp_length': 'EmpLength', 'loan_intent':'Intent', 'loan_grade':'Grade',
    'loan_amnt':'Amount', 'loan_int_rate':'Rate', 'loan_status':'Status',
    'loan_percent_income':'PercentIncome', 'cb_person_default_on_file':'DefaultHist',
    'cb_person_cred_hist_length':'CredHist'
})

df.insert(0, 'PersonID', ['PER_' + str(i).zfill(5) for i in range(1, len(df) + 1)])

print("=== TỶ LỆ DỮ LIỆU KHUYẾT (%) ===")
missing_percent = (df.isnull().sum() / len(df)) * 100
print(missing_percent[missing_percent > 0].round(2))

print("\n=== TƯƠNG QUAN VỚI BIẾN MỤC TIÊU (STATUS) ===")
corr_matrix = df.corr(numeric_only=True)
print(corr_matrix['Status'][['EmpLength', 'Rate']].round(4))
print("====================================================================\n")

df = df.dropna(subset=['EmpLength']).copy()
df['Rate'] = df['Rate'].fillna(df.groupby('Grade')['Rate'].transform('median'))

for col in ['Home', 'Intent', 'Grade', 'DefaultHist']:
    df[col] = df[col].astype(str).str.strip().str.upper()

df_clean = df[
    (df['Age'] >= 18) & (df['Age'] <= 100) &
    (df['EmpLength'] <= df['Age'] - 18) &
    (df['Income'] > 0) &
    (df['Amount'] > 0) &
    (df['PercentIncome'] > 0) & (df['PercentIncome'] < 1) &
    (df['CredHist'] <= df['Age'] - 18)
].copy()

df_clean['Income'] = df_clean['Income'].astype(float)
df_clean['Amount'] = df_clean['Amount'].astype(float)
print(df_clean.info())
print("✅ ĐÃ LÀM SẠCH DỮ LIỆU THÀNH CÔNG!")
print(f"-> Tổng số dòng hợp lệ giữ lại: {len(df_clean)}")

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

# BƯỚC 3: KHÁM PHÁ DỮ LIỆU (EDA - EXPLORATORY DATA ANALYSIS)
print("=== MA TRẬN TƯƠNG QUAN (XEM BIẾN NÀO ẢNH HƯỞNG ĐẾN NỢ XẤU) ===")
correlation_matrix = df_clean.corr(numeric_only=True)
print(round(correlation_matrix['Status'].sort_values(ascending=False), 4))
print("-" * 60)

# --- BIỂU ĐỒ 1: MỐI QUAN HỆ GIỮA CÁC BIẾN PHÂN LOẠI VÀ NỢ XẤU ---
plt.figure(figsize=(18, 10))

# 1. Biểu đồ Sở hữu nhà
plt.subplot(2, 2, 1)
sns.countplot(data=df_clean, x='Home', hue='Status', palette='Set2')
plt.title('Sở hữu nhà và Nợ xấu', fontsize=12, fontweight='bold')
plt.xlabel('Home')
plt.ylabel('Number of customers')

# 2. Biểu đồ Mục đích vay
plt.subplot(2, 2, 2)
sns.countplot(data=df_clean, x='Intent', hue='Status', palette='magma')
plt.xticks(rotation=30)
plt.title('Mục đích vay và Nợ xấu', fontsize=12, fontweight='bold')
plt.xlabel('Intent')
plt.ylabel('Number of customers')

# 3. Biểu đồ Hạng tín dụng
plt.subplot(2, 2, 3)
sns.countplot(data=df_clean, x='Grade', hue='Status', order=sorted(df_clean['Grade'].unique()), palette='viridis')
plt.title('Hạng tín dụng vs Nợ xấu', fontsize=12, fontweight='bold')
plt.xlabel('Grade (A là tốt nhất, G là tệ nhất)')
plt.ylabel('Number of customers')

plt.tight_layout()
plt.show()

# --- THỐNG KÊ MÔ TẢ ĐỂ TÌM NGƯỠNG CẮT NGOẠI LỆ ---
print("=== THỐNG KÊ MÔ TẢ CỘT THU NHẬP (INCOME) ===")
# In ra các thông số cơ bản (Min, Max, Trung bình, Q1, Q2, Q3)
print(df_clean['Income'].describe().apply(lambda x: format(x, 'f')))
print("-" * 40)

# Tính xem 95% khách hàng nằm ở mức thu nhập nào
muc_95_phantram = df_clean['Income'].quantile(0.95)
print(f"-> 95% khách hàng có thu nhập dưới mức: {muc_95_phantram:,.0f}")
print("=> KẾT LUẬN: Chọn ngưỡng cắt 200,000 để trực quan hóa là hoàn toàn hợp lý!")
print("-" * 60)

# --- BIỂU ĐỒ 2: PHÂN PHỐI THU NHẬP VÀ SỐ TIỀN VAY ---
plt.figure(figsize=(16, 5))
plt.subplot(1, 2, 1)
sns.boxplot(data=df_clean[df_clean['Income'] < 200000], x='Status', y='Income', palette='Set1')
plt.title('Phân phối Thu nhập theo Trạng thái nợ', fontsize=12, fontweight='bold')

plt.subplot(1, 2, 2)
sns.boxplot(data=df_clean, x='Status', y='Amount', palette='PuBu')
plt.title('Phân phối Số tiền vay theo Trạng thái nợ', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.show()

# --- BIỂU ĐỒ 3: MẬT ĐỘ LÃI SUẤT VÀ TỶ LỆ VAY/THU NHẬP ---
plt.figure(figsize=(16, 5))

# 1. Histplot Lãi suất bên trái
plt.subplot(1, 2, 1)
sns.histplot(data=df_clean, x='Rate', hue='Status', kde=True, multiple="layer", palette='Set1', alpha=0.5)
plt.title('Mật độ Lãi suất theo Trạng thái nợ', fontsize=12, fontweight='bold')
plt.xlabel('Lãi suất khoản vay (%)')
plt.ylabel('Mật độ khách hàng')

# 2. Histplot Tỷ lệ Vay/Thu nhập bên phải
plt.subplot(1, 2, 2)
sns.histplot(data=df_clean, x='PercentIncome', hue='Status', kde=True, multiple="layer", palette='Dark2', alpha=0.5)
plt.title('Mật độ Tỷ lệ Vay / Thu nhập theo Trạng thái nợ', fontsize=12, fontweight='bold')
plt.xlabel('Tỷ lệ Số tiền vay / Thu nhập')
plt.ylabel('Mật độ khách hàng')

plt.tight_layout()
plt.show()

# BƯỚC 4: BIẾN ĐỔI DỮ LIỆU (DATA TRANSFORMATION) - FEATURE ENGINEERING
df_features = df_clean.copy()

age_bins = [0, 25, 40, 60, 100]
age_labels = ['18-25', '26-40', '41-60', 'ABOVE 60']
df_features['Age_Group'] = pd.cut(df_features['Age'], bins=age_bins, labels=age_labels)

df_features['Income_Group'] = pd.qcut(df_features['Income'], q=3, labels=['LOW INCOME', 'MEDIUM INCOME', 'HIGH INCOME'])

financial_bins = [0, 0.20, 0.30, 1.0]
financial_labels = ['SAFE (<20%)', 'WARNING (20-30%)', 'HIGH RISK (>30%)']
df_features['Loan_Burden'] = pd.cut(df_features['PercentIncome'], bins=financial_bins, labels=financial_labels)

df_features.to_csv('/content/drive/MyDrive/DoAnNganh/DuLieu/credit_risk_for_powerbi.csv', index=False)
print("✅ ĐÃ XUẤT FILE DẠNG CHỮ CHO POWER BI THÀNH CÔNG!")
print("-> Đường dẫn: /content/drive/MyDrive/DoAnNganh/DuLieu/credit_risk_for_powerbi.csv")

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# 1. TẠO BẢNG DỮ LIỆU CHUẨN TRỊ CHO ML/AI
df_ai = df_features.copy()

cols_to_drop_for_ai = ['PersonID', 'Age_Group', 'Income_Group', 'Loan_Burden']
df_ai = df_ai.drop(columns=[col for col in cols_to_drop_for_ai if col in df_ai.columns], axis=1)

# 2. MÃ HÓA BIẾN (ENCODING)
df_ai['Grade'] = df_ai['Grade'].map({'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7})
df_ai['DefaultHist'] = df_ai['DefaultHist'].map({'Y': 1, 'N': 0})

nominal_cols = ['Home', 'Intent']
df_ai = pd.get_dummies(df_ai, columns=nominal_cols, drop_first=True, dtype=int)

df_ai.to_csv('/content/drive/MyDrive/DoAnNganh/DuLieu/credit_risk_processed_for_AI.csv', index=False)

# 3. CHIA TẬP TRAIN / TEST (80% - 20%)
X = df_ai.drop('Status', axis=1)
y = df_ai['Status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 4. CHUẨN HÓA MIN-MAX SCALING (CHỐNG RÒ RỈ DỮ LIỆU)
numeric_cols = ['Age', 'Income', 'EmpLength', 'Amount', 'Rate', 'PercentIncome', 'CredHist']
scaler = MinMaxScaler()

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

print("✅ ĐÃ CHUẨN BỊ DỮ LIỆU AI XONG (KHÔNG BỊ DATA LEAKAGE & ĐA CỘNG TUYẾN)!")
print(f"-> Kích thước tập huấn luyện (X_train): {X_train.shape}")
print(f"-> Kích thước tập kiểm tra (X_test): {X_test.shape}")
# # Xem kích thước của bảng dữ liệu gốc sau khi làm sạch
# print(df_clean.shape)
# # Hoặc xem kích thước bảng dữ liệu chuẩn bị cho AI
# print(df_ai.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, roc_auc_score

# BƯỚC 5: MÔ HÌNH HÓA (DATA MODELING)
# Mô hình 1: Logistic Regression (Baseline - Tính diễn giải cao)
log_model = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
log_model.fit(X_train, y_train)
y_pred_log = log_model.predict(X_test)
y_prob_log = log_model.predict_proba(X_test)[:, 1]

# Mô hình 2: Random Forest (Nâng cấp - Khả năng bắt mạch dữ liệu phi tuyến tính tốt hơn)
rf_model = RandomForestClassifier(n_estimators=100, class_weight='balanced', max_depth=10, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

# BƯỚC 6: ĐÁNH GIÁ MÔ HÌNH (MODEL EVALUATION)
print("=== KẾT QUẢ MÔ HÌNH LOGISTIC REGRESSION ===")
print(classification_report(y_test, y_pred_log))
print("\n=== KẾT QUẢ MÔ HÌNH RANDOM FOREST ===")
print(classification_report(y_test, y_pred_rf))

# --- ĐƯỜNG CONG ROC SO SÁNH 2 MÔ HÌNH ---
fpr_log, tpr_log, _ = roc_curve(y_test, y_prob_log)
auc_log = roc_auc_score(y_test, y_prob_log)
print("AUC Logistic:", auc_log)
fpr_rf, tpr_rf, _ = roc_curve(y_test, y_prob_rf)
auc_rf = roc_auc_score(y_test, y_prob_rf)
print("AUC Random Forest:", auc_rf)

plt.figure(figsize=(9, 6))
plt.plot(fpr_log, tpr_log, label=f'Logistic Regression (AUC = {auc_log:.3f})', color='blue', linestyle='--')
plt.plot(fpr_rf, tpr_rf, label=f'Random Forest (AUC = {auc_rf:.3f})', color='green', linewidth=2)
plt.plot([0, 1], [0, 1], 'k--', alpha=0.5)
plt.title('SO SÁNH KHẢ NĂNG DỰ BÁO NỢ XẤU (ĐƯỜNG CONG ROC)', fontsize=13, fontweight='bold')
plt.xlabel('Tỷ lệ bắt nhầm người tốt (False Positive Rate)')
plt.ylabel('Độ nhạy bắt nợ xấu (True Positive Rate)')
plt.legend(loc='lower right', fontsize=11)
plt.show()

# ---  TOP 10 YẾU TỐ ẢNH HƯỞNG ĐẾN NỢ XẤU (RANDOM FOREST) ---
rf_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=rf_importance.head(10), palette='viridis', hue='Feature', legend=False)
plt.title('TOP 10 YẾU TỐ QUYẾT ĐỊNH RỦI RO NỢ XẤU (Random Forest)', fontsize=13, fontweight='bold')
plt.xlabel('Mức độ quan trọng')
plt.ylabel('Các đặc trưng tài chính')
plt.show()

# ---  MA TRẬN NHẦM LẪN (CONFUSION MATRIX) ---
cm_rf = confusion_matrix(y_test, y_pred_rf)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Greens', cbar=False,
            xticklabels=['Tốt (0)', 'Nợ xấu (1)'],
            yticklabels=['Tốt (0)', 'Nợ xấu (1)'])
plt.title('Ma Trận Nhầm Lẫn - Mô Hình Random Forest', fontsize=12, fontweight='bold')
plt.xlabel('Dự báo của AI')
plt.ylabel('Thực tế Khách hàng')
plt.show()

import numpy as np

# Đã điền đủ 17 con số cho khớp với 17 cột của X_train
# (Bà có thể tự thay đổi các con số này thành thông tin thật nếu muốn)
thong_tin_ong_A = [[0.45, 3, 20000, 0.15, 1, 15000, 5, 0, 1, 30, 0, 0, 0, 0, 0, 0, 0]]

# Đưa vào mô hình rf_model để dự báo xác suất
xac_suat = rf_model.predict_proba(thong_tin_ong_A)

print("Xác suất dự báo [Tốt (0) - Nợ xấu (1)]:")
print(xac_suat)
